@startuml
'https://plantuml.com/sequence-diagram

autonumber
title 基于springboot API请求处理流程
/'
API控制器正常处理
'/
==场景一：API控制器正常处理==
autonumber 1 1 "步骤："
actor -> ContentCachingWrapperFilter:发送API请求
ContentCachingWrapperFilter -> DefaultRequestMethodInterceptor:全局请求缓存|阶段标识Parameter设置
DefaultRequestMethodInterceptor -> ApiController:API接口日志记录开始|设置阶段标识Controller
DefaultRequestMethodInterceptor <-- ApiController:API接口执行完成
DefaultResponseAdviceInterceptor <- DefaultRequestMethodInterceptor:API返回值包装
ContentCachingWrapperFilter <-- DefaultResponseAdviceInterceptor:移除上下文阶段标记
actor <- ContentCachingWrapperFilter: API返回结果
/'
API控制器参数校验异常
'/
==场景二：API控制器参数校验异常==
autonumber 1 1 "步骤："
actor -> ContentCachingWrapperFilter:发送API请求
ContentCachingWrapperFilter -[#red]> DefaultGlobalExceptionHandler:全局请求缓存|阶段标识Parameter设置-参数或Method异常
DefaultResponseAdviceInterceptor <-[#red]- DefaultGlobalExceptionHandler:API异常返回值包装处理
ContentCachingWrapperFilter <-[#red]- DefaultResponseAdviceInterceptor:移除上下文阶段标记
actor <- ContentCachingWrapperFilter: API返回结果
/'
API控制器内部异常
'/
==场景三：API控制器内部异常==
autonumber 1 1 "步骤："
actor -> ContentCachingWrapperFilter:发送API请求
ContentCachingWrapperFilter -> DefaultRequestMethodInterceptor:全局请求缓存|阶段标识Parameter设置
DefaultRequestMethodInterceptor -> ApiController:API接口日志记录开始|设置阶段标识Controller
DefaultRequestMethodInterceptor <-[#red]- ApiController:API内部发生异常
DefaultGlobalExceptionHandler <[#red]- DefaultRequestMethodInterceptor:API拦截器记录日志结束，抛出控制器返回的异常
DefaultResponseAdviceInterceptor <-[#red]- DefaultGlobalExceptionHandler:API异常返回值包装处理
ContentCachingWrapperFilter <-[#red]- DefaultResponseAdviceInterceptor:执行完成返回
actor <- ContentCachingWrapperFilter: API返回结果
@enduml