<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.github.mingyang66</groupId>
        <artifactId>emily-parent</artifactId>
        <version>${revision}</version>
        <relativePath>../emily-parent/pom.xml</relativePath>
    </parent>

    <artifactId>emily-spring-boot-project</artifactId>
    <name>emily-spring-boot-project</name>
    <description>Emily Spring Boot Project</description>
    <packaging>pom</packaging>
    <modules>
        <module>logger-spring-boot-starter</module>
        <module>aop-spring-boot-starter</module>
        <module>redis-spring-boot-starter</module>
        <module>datasource-spring-boot-starter</module>
        <module>amqp-spring-boot-starter</module>
        <module>transfer-spring-boot-starter</module>
        <module>validation-spring-boot-starter</module>
        <module>web-spring-boot-starter</module>
        <module>tracing-spring-boot-starter</module>
        <module>rateLimiter-spring-boot-starter</module>
        <module>i18n-spring-boot-starter</module>
        <module>desensitize-spring-boot-starter</module>
        <module>security-spring-boot-starter</module>
    </modules>

</project>